### ISSUE TITLE
关于“只匹配【?】前部分” 不行的问题修复

### ISSUE THREAD

**Issue by ericisme** [flftfqwxf/mock-server#1]
修改了src/api/controller/index.js第25行。
由原来的
const tempdata = await this.model('mockserver').where("api_url regexp '^" + url + "\\\\?'").select();
改成
const tempdata = await this.model('mockserver').where("api_url regexp '^" + url + "\\?'").select();

**Comment by flftfqwxf** [comment]
@ericisme 经测试功能正常，是否是mysql版本原因？
我本地开发版本为：mysql  Ver 14.14 Distrib 5.7.14, for osx10.11 (x86_64) using  EditLine wrapper
另修改了功能:
  只匹配【?】则以下都会匹配: website/articles/comment?post_id=12 website/articles/comment?post_id=13 website/articles/comment?xxx=12
  修改为：

    website/articles/comment 或website/articles/comment?post_id=12 或 website/articles/comment?xxx=12
