### ISSUE TITLE
支持在web页中直接做调用吗

### ISSUE THREAD

**Issue by 15174834** [flftfqwxf/mock-server#3]
支持在web页中直接做请求调用吗，像taobao rap一样

**Comment by flftfqwxf** [comment]
@15174834 不太明白你表达的什么，如果你是指直接在WEB项目中AJAX请求这个项目里的接口吗？

**Comment by flftfqwxf** [comment]
@15174834 刚刚添加了功能，允许跨域访问接口

**Comment by 15174834** [comment]
小弟在次跪拜了 ：)
