### ISSUE TITLE
使用过程遇到问题，求解答

### ISSUE THREAD

**Issue by baishengmei** [flftfqwxf/mock-server#5]
npm install之后，需要连接数据库mysql的目的是什么啊？这一步是必须的吗？
npm start后，没有出现截图中的界面是为什么啊？

**Comment by flftfqwxf** [comment]
@baishengmei 连接数据库是必须，所有数据都存储在MYSQL数据库中
今天有提交过新代码，并修改过数据库，建议使用新版本代码及重新导入新版本数据库
问题截图没有更新，但对应目前截图功能都存在，请以实际页面为准

**Comment by baishengmei** [comment]
您好，我执行npm start后，并未出现界面？正常流程是这样的吗？控制台显示App Environment为development

**Comment by flftfqwxf** [comment]
@baishengmei 执行后，控制台会输出 Server running at http://127.0.0.1:8033/
使用此地址访问
