### ISSUE TITLE
Ace编辑器是不是有bug呀

### ISSUE THREAD

**Issue by Andyliwr** [flftfqwxf/mock-server#6]
1. Ace编辑器没法正常输入
2. 现在ace给出的版本，好像也没有分codeEditor以及treeEditor，而且个人觉得一个其实也挺好的，详情：https://github.com/josdejong/jsoneditor/blob/master/examples/08_custom_ace.html
3. 作者怎么处理post请求的？好像模拟起来结果还是get请求。难道只能实现返回写死的数据？可以不可以获取post请求里的数据，在返回项中对这些数据做些处理，然后再返回
4. 现在api管理的软件感觉很多呀，比如postman还有swaggerUI，感觉软件可以专注mock，那些接口描述的输入是不是可以去掉？

**Comment by flftfqwxf** [comment]
@Andyliwr  
Ace编辑器在中文时，在左侧的输入中好像会有问题，使用右边的tree不会有问题
post请求，是你在自己的代码里写post，然后代理到服务上，在系统内直接发送数据都是GET
比如：
你写一个 ajax:

 ```
$.ajax({
            type: "post",
            dataType: "json",
            data: {"exam_type": exam_type, "position_id": positionID},
            url: "/examapi/requestExamURL",
            success: function(data, textStatus) {
                // console.log(data);
                _this.showFullScreenDialog(data);
            },
            complete: function(XMLHttpRequest, textStatus) {
            },
            error: function() {
                $.commonTips('操作失败，刷新重试', 'danger', 3);
            }
        });

```

/examapi/requestExamURL 此url代理后，并开启二次代理后，会把AJAX的参数（根据全局设置的HEADER参数代理），代理到二次代理上，并正常返回数据。
而直接点击打开URL，目前并没有带参数，后面会加一个接口测试的功能（类似POSTMAN），来发送POST等参数，以此来测试接口数据正确性

**Comment by flftfqwxf** [comment]
@Andyliwr  jsoneditor的中文BUG在新片本好象已经解决，之后我会更新版本
